[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
members = [
    "xpnft",
    "xpbridge",
    "currency-data-oracle",
    "xpnft-royalty",
    "collection-creator"
]
