[package]
name = "collection-creator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "4.1.1", features = ["unstable"]}
near-contract-standards = "4.1.1"

[dev-dependencies]